var unionvlc__event__t_1_1vlc__event__type__specific =
[
    [ "input_item_error_when_reading_changed", "structvlc__event__t_1_1vlc__event__type__specific_1_1input__item__error__when__reading__changed.html", "structvlc__event__t_1_1vlc__event__type__specific_1_1input__item__error__when__reading__changed" ],
    [ "vlc_input_item_duration_changed", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__input__item__duration__changed.html", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__input__item__duration__changed" ],
    [ "vlc_input_item_info_changed", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__input__item__info__changed.html", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__input__item__info__changed" ],
    [ "vlc_input_item_meta_changed", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__input__item__meta__changed.html", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__input__item__meta__changed" ],
    [ "vlc_input_item_name_changed", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__input__item__name__changed.html", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__input__item__name__changed" ],
    [ "vlc_input_item_preparsed_changed", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__input__item__preparsed__changed.html", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__input__item__preparsed__changed" ],
    [ "vlc_input_item_subitem_added", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__input__item__subitem__added.html", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__input__item__subitem__added" ],
    [ "vlc_input_item_subitem_tree_added", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__input__item__subitem__tree__added.html", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__input__item__subitem__tree__added" ],
    [ "vlc_input_selected_stream_changed", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__input__selected__stream__changed.html", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__input__selected__stream__changed" ],
    [ "vlc_input_state_changed", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__input__state__changed.html", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__input__state__changed" ],
    [ "vlc_services_discovery_ended", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__services__discovery__ended.html", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__services__discovery__ended" ],
    [ "vlc_services_discovery_item_added", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__services__discovery__item__added.html", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__services__discovery__item__added" ],
    [ "vlc_services_discovery_item_removed", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__services__discovery__item__removed.html", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__services__discovery__item__removed" ],
    [ "vlc_services_discovery_started", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__services__discovery__started.html", "structvlc__event__t_1_1vlc__event__type__specific_1_1vlc__services__discovery__started" ],
    [ "input_item_duration_changed", "unionvlc__event__t_1_1vlc__event__type__specific.html#a4403f14542f1220c59a8b53765c21e6d", null ],
    [ "input_item_error_when_reading_changed", "unionvlc__event__t_1_1vlc__event__type__specific.html#a14c22ace9d6005802e0069a4bcfd9e7b", null ],
    [ "input_item_info_changed", "unionvlc__event__t_1_1vlc__event__type__specific.html#a7896f0c084aed840f62899e4b1356318", null ],
    [ "input_item_meta_changed", "unionvlc__event__t_1_1vlc__event__type__specific.html#a94ec3626f4f76434e85f85894360b24a", null ],
    [ "input_item_name_changed", "unionvlc__event__t_1_1vlc__event__type__specific.html#a2408003092ea9360081ec48a2f70deb7", null ],
    [ "input_item_preparsed_changed", "unionvlc__event__t_1_1vlc__event__type__specific.html#a31558233c689915c77eb1ed5050648c8", null ],
    [ "input_item_subitem_added", "unionvlc__event__t_1_1vlc__event__type__specific.html#aa038992d974f8380fad7e1ddd762191d", null ],
    [ "input_item_subitem_tree_added", "unionvlc__event__t_1_1vlc__event__type__specific.html#a7468ff2de42cf0d73ef7b29c450bc9dc", null ],
    [ "input_selected_stream_changed", "unionvlc__event__t_1_1vlc__event__type__specific.html#aae1e7718b7687979caf02e1b15a6ccbd", null ],
    [ "input_state_changed", "unionvlc__event__t_1_1vlc__event__type__specific.html#afa519c7abc2a4f2fc6080da136aeb38d", null ],
    [ "services_discovery_ended", "unionvlc__event__t_1_1vlc__event__type__specific.html#adbc35a09189fe169f64e82defaebee60", null ],
    [ "services_discovery_item_added", "unionvlc__event__t_1_1vlc__event__type__specific.html#a810e0249fe302d2732f46bd306e3f055", null ],
    [ "services_discovery_item_removed", "unionvlc__event__t_1_1vlc__event__type__specific.html#ae42eb2c4e95e1d59182bdfc52f5766b5", null ],
    [ "services_discovery_started", "unionvlc__event__t_1_1vlc__event__type__specific.html#a724e83182142a9a7a93321606f922bdd", null ]
];